// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv8UDZNT8XgLvQwGfh5HOs-mJxzpaIsss',
    appId: '1:746006227563:web:424d417cbba9da460a1f2e',
    messagingSenderId: '746006227563',
    projectId: 'fastapp-adb33',
    authDomain: 'fastapp-adb33.firebaseapp.com',
    storageBucket: 'fastapp-adb33.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH6yDNq6gGvORKYMJHsOm-5ExKmuhQO6s',
    appId: '1:746006227563:android:652a1f821f7306060a1f2e',
    messagingSenderId: '746006227563',
    projectId: 'fastapp-adb33',
    storageBucket: 'fastapp-adb33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRuZLaWlVogwJLd9m-H4DrWf8ycikRF-A',
    appId: '1:746006227563:ios:133d7b701f8b9c510a1f2e',
    messagingSenderId: '746006227563',
    projectId: 'fastapp-adb33',
    storageBucket: 'fastapp-adb33.appspot.com',
    iosClientId: '746006227563-g6j62sqdf9nm3gbpe7to2o17t5ecl702.apps.googleusercontent.com',
    iosBundleId: 'com.example.slack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRuZLaWlVogwJLd9m-H4DrWf8ycikRF-A',
    appId: '1:746006227563:ios:133d7b701f8b9c510a1f2e',
    messagingSenderId: '746006227563',
    projectId: 'fastapp-adb33',
    storageBucket: 'fastapp-adb33.appspot.com',
    iosClientId: '746006227563-g6j62sqdf9nm3gbpe7to2o17t5ecl702.apps.googleusercontent.com',
    iosBundleId: 'com.example.slack',
  );
}
